[pytest]
# Cấu hình bộ lọc cảnh báo.
# Dòng "ignore" được thêm vào để xử lý một cảnh báo "cứng đầu"
# từ module 'multiprocessing' trên macOS.
filterwarnings =
    ignore::pytest.PytestConfigWarning
    ignore:.*semaphore objects.*:UserWarning
    ignore:.*multiprocessing.*:UserWarning